---
title: "Publication"
---

I would like to express my sincere gratitude to all of my collaborators for their invaluable contributions.

A publication list can also be found from [Google Scholar](https://scholar.google.com/citations?user=BD0ESZoAAAAJ&hl=en&oi=ao)

Annotations: \# first author; \* corresponding author


## 2024

- Raisinghani, N.; Alshahrani, M.; Gupta, G.; Tian, H.; **Xiao, S.**; Tao, P.; Verkhivker, G. Interpretable Atomistic Prediction and Functional Analysis of Conformational Ensembles and Allosteric States in Protein Kinases Using AlphaFold2 Adaptation with Randomized Sequence Scanning and Local Frustration Profiling. *bioRxiv*, 2024. [[link](https://doi.org/10.1101/2024.02.15.580591)]
- **Xiao, S.**^\#\*^; Mohamed, M.; Verkhivker, G.; Zoltolwski, B.; Tao, P. *β*-sheets mediate the conformational change and allosteric signal transmission between the *As*LOV2 termini. *Journal of Computational Chemistry*, 2024, Accepted. [[link](https://doi.org/10.1002/jcc.27344)]
- Raisinghani, N.; Alshahrani, M.; Gupta, G.; **Xiao, S.**; Tao, P.; Verkhivker, G. AlphaFold2-Enabled Atomistic Modeling of Structure, Conformational Ensembles, and Binding Energetics of the SARS-CoV-2 Omicron BA.2.86 Spike Protein with ACE2 Host Receptor and Antibodies: Compensatory Functional Effects of Binding Hotspots in Modulating Mechanisms of Receptor Binding and Immune Escape. *Journal of Chemical Information and Modeling*, 2024, 5, 1657-1681. [[link](https://doi.org/10.1021/acs.jcim.3c01857)]

## 2023

- Raisinghani, N.; Alshahrani, M.; Gupta, G.; **Xiao, S.**; Tao, P.; Verkhivker, G. Accurate Characterization of Conformational Ensembles and Binding Mechanisms of the SARS-CoV-2 Omicron BA.2 and BA.2.86 Spike Protein with the Host Receptor and Distinct Classes of Antibodies Using AlphaFold2-Augmented Integrative Computational Modeling. *bioRxiv*, 2023. [[link](https://doi.org/10.1101/2023.11.18.567697)]
- Alshahrani, M.; Gupta, G.; **Xiao, S.**; Tao, P.; Verkhivker, G. Comparative Analysis of Conformational Dynamics and Systematic Characterization of Cryptic Pockets in the SARS-CoV-2 Omicron BA.2, BA.2.75 and XBB.1 Spike Complexes with the ACE2 Host Receptor: Confluence of Binding and Structural Plasticity in Mediating Networks of Conserved Allosteric Sites. *Viruses*, 2023, 15(10), 2073. [[link](https://doi.org/10.3390/v15102073)]
- Alshahrani, M.; Gupta, G.; **Xiao, S.**; Tao, P.; Verkhivker, G. Examining Functional Linkages Between Conformational Dynamics, Protein Stability and Evolution of Cryptic Binding Pockets in the SARS-CoV-2 Omicron Spike Complexes with the ACE2 Host Receptor: Recombinant Omicron Variants Mediate Variability of Conserved Allosteric Sites and Binding Epitopes. *bioRxiv*, 2023. [[link](https://doi.org/10.1101/2023.09.11.557205)]
- **Xiao, S.**^\#^; Alshahrani, M; Gupta, G; Tao, P; Verkhivker, G. Markov State Models and Perturbation-Based Approaches Reveal Distinct Dynamic Signatures and Hidden Allosteric Pockets in the Emerging SARS-Cov-2 Spike Omicron Variants Complexes with the Host Receptor: The Interplay of Dynamics and Convergent Evolution Modulates Allostery and Functional Mechanisms. *Journal of Chemical Information and Modeling*, 2023, 16, 5272–5296. [[link](https://doi.org/10.1021/acs.jcim.3c00778)]
- Verkhivker, G.; Alshahrani, M; Gupta, G; **Xiao, S**; Tao, P. Probing Conformational Landscapes of Binding and Allostery in the SARS-CoV-2 Omicron Variant Complexes Using Microsecond Atomistic Simulations and Perturbation-Based Profiling Approaches: Hidden Role of Omicron Mutations as Modulators of Allosteric Signaling and Epistatic Relationships. *Physical Chemistry Chemical Physics*, 2023, 25, 21245-21266. [[link](https://doi.org/10.1039/D3CP02042H)]
- Tian, H.; **Xiao, S.**; Jiang, X.; Tao, P. PASSerRank: prediction of allosteric sites with learning to rank. *Journal of Computational Chemistry*, 2023, 44, 2223-2229. [[link](https://doi.org/10.1002/jcc.27193)]
- Tian, H.; **Xiao, S.**; Jiang, X.; Tao, P. PASSer: Fast and Accurate Prediction of Protein Allosteric Sites. *Nucleic Acids Research*, 2023, 51, W427–W431. [[link](https://doi.org/10.1093/nar/gkad303)]
- Verkhivker, G.; Alshahrani, M.; Gupta, G.; **Xiao, S.**; Tao, P. From Deep Mutational Mapping of Allosteric Protein Landscapes to Deep Learning of Allostery and Hidden Allosteric Sites: Zooming in on “Allosteric Intersection” of Biochemical and Big Data Approaches. *International Journal of Molecular Sciences*, 2023, 24, 7747. [[link](https://doi.org/10.3390/ijms24097747)]
- Li, H.; Tian, H; Chen, Y.; **Xiao, S.**, Zhao, X;, Gao, Y; Zhang, L. Analyzing and Predicting the Viscosity of Polymer Nanocomposites in the Conditions of Temperature, Shear Rate, and Nanoparticle Loading with Molecular Dynamics Simulations and Machine Learning. *The Journal of Physical Chemistry B*, 2023, 127, 3596–3605. [[link](https://doi.org/10.1021/acs.jpcb.3c01697)]
- **Xiao, S.**^\#^; Song, Z.; Tian, H.; Tao, P. Assessments of Variational Autoencoder in Protein Conformation Exploration. *Journal of Computational Biophysics and Chemistry*, 2023, 22, 489-501. [[link](https://doi.org/10.1142/S2737416523500217)]
- Tian, H.; Jiang, X.; **Xiao, S.**; La Force, H.; Larson, E. C.; Tao, P. LAST: Latent Space-Assisted Adaptive Sampling for Protein Trajectories. *Journal of Chemical Information and Modeling*, 2023, 63, 67–75. [[link](https://doi.org/10.1021/acs.jcim.2c01213)]

## 2022

- **Xiao, S.**^\#\*^; Verkhivker, G.; Tao, P. Machine Learning and Protein Allostery. *Trends in Biochemical Sciences*, 2022, 48, 375-390. [[link](https://doi.org/10.1016/j.tibs.2022.12.001)]
- **Xiao, S.**^\#^; Tian, H.; Tao, P. PASSer2.0: Accurate Prediction of Protein Allosteric Sites Through Automated Machine Learning. *Frontiers in Molecular Biosciences*, 2022, 9. [[link](https://doi.org/10.3389/fmolb.2022.879251)]

## 2021

- Tian, H.; Jiang, X.; Trozzi, F.; **Xiao, S.**; Larson, E. C.; Tao, P. Explore Protein Conformational Space With Variational Autoencoder. *Frontiers in Molecular Biosciences*, 2021, 8. [[link](https://doi.org/10.3389/fmolb.2021.781635)]
