---
title: "Science"
---

It was great to pursue a Ph.D. degree following my childhood dream.

I obtained his Ph.D. in Theoretical and Computational Chemistry at [Southern Methodist University][smu] advised by Dr. [Peng Tao][ptao].

My Ph.D. work focuses on the combination of computational structural biology and modern machine learning techniques. The research topic covers protein dynamics, protein allostery, drug desgin, and applications of machine learning and deep learning.

Throughout my past study and research, some other topics I've worked on include perovskite solar cells, composite material with carbon nanotube modifications, chemical catalysis carried by ayered double hydroxides, etc.

[smu]:<https://www.smu.edu/>
[ptao]:<https://www.smu.edu/Dedman/Academics/Departments/Chemistry/People/Faculty/PengTao>


## Peer Reviews

I am willing to review papers related to my research interest and experience.

Some past peer reviews include:

- Molecules
- Computational and Structural Biotechnology Reports
- Journal of Molecular Graphics and Modelling (3)
- Drug Delivery
- Scientific Reports (2)
- Discover Artificial Intelligence (2)
- International Conference on Learning Representations (ICLR)
- International Journal of Biological Macromolecules
- Discover Sustainability
- Computational and Structural Biotechnology Journal
- Expert Review of Anti-Infective Therapy (2)
- Journal of Cheminformatics (3)


## Publications

I would like to express my sincere gratitude to all of my collaborators for their invaluable contributions.

A publication list can also be found from [Google Scholar](https://scholar.google.com/citations?user=BD0ESZoAAAAJ&hl=en&oi=ao)

Annotations: \# first author; \* corresponding author

- **Xiao, S.**; Alshahrani, M.; Hu, G.; Tao, P.; Verkhivker, G. Accurate Characterization of the Allosteric Energy Landscapes, Binding Hotspots and Long-Range Communications for KRAS Complexes with Effector Proteins : Integrative Approach Using Microsecond Molecular Dynamics, Deep Mutational Scanning of Binding Energetics and Allosteric Network Modeling. *bioRxiv*, 2025. [[link](https://doi.org/10.1101/2025.01.27.635141)]
- Raisinghani, N.; Alshahrani, M.; Gupta, G.; Tian, H.; **Xiao, S.**; Tao, P.; Verkhivker, G. Probing Functional Allosteric States and Conformational Ensembles of the Allosteric Protein Kinase States and Mutants: Atomistic Modeling and Comparative Analysis of AlphaFold2, OmegaFold, and AlphaFlow Approaches and Adaptations. *The Journal of Physical Chemistry B*, 2024, 128(45), 11088–11107. [[link](https://doi.org/10.1021/acs.jpcb.4c04985)]
- Raisinghani, N.; Alshahrani, M.; Gupta, G.; Tian, H.; **Xiao, S.**; Tao, P.; Verkhivker, G. Integration of a Randomized Sequence Scanning Approach in AlphaFold2 and Local Frustration Profiling of Conformational States Enable Interpretable Atomistic Characterization of Conformational Ensembles and Detection of Hidden Allosteric States in the ABL1 Protein Kinase. *Journal of Chemical Theory and Computation*, 2024, 20(12), 5317–5336. [[link](https://doi.org/10.1021/acs.jctc.4c00222)]
- Raisinghani, N.; Alshahrani, M.; Gupta, G.; **Xiao, S.**; Tao, P.; Verkhivker, G. Exploring conformational landscapes and binding mechanisms of convergent evolution for the SARS-CoV-2 spike Omicron variant complexes with the ACE2 receptor using AlphaFold2-based structural ensembles and molecular dynamics simulations. *Physical Chemistry Chemical Physics*, 2024, 26, 17720-17744. [[link](https://doi.org/10.1039/D4CP01372G)]
- Raisinghani, N.; Alshahrani, M.; Gupta, G.; **Xiao, S.**; Tao, P.; Verkhivker, G. AlphaFold2 Predictions of Conformational Ensembles and Atomistic Simulations of the SARS-CoV-2 Spike XBB Lineages Reveal Epistatic Couplings between Convergent Mutational Hotspots that Control ACE2 Affinity. *The Journal of Physical Chemistry B*, 2024, 128(19), 4696-4715. [[link](https://doi.org/10.1021/acs.jpcb.4c01341)]
- **Xiao, S.**^\#\*^; Mohamed, M.; Verkhivker, G.; Zoltolwski, B.; Tao, P. *β*-sheets mediate the conformational change and allosteric signal transmission between the *As*LOV2 termini. *Journal of Computational Chemistry*, 2024, 45, 1493-1504. [[link](https://doi.org/10.1002/jcc.27344)]
- Raisinghani, N.; Alshahrani, M.; Gupta, G.; **Xiao, S.**; Tao, P.; Verkhivker, G. AlphaFold2-Enabled Atomistic Modeling of Structure, Conformational Ensembles, and Binding Energetics of the SARS-CoV-2 Omicron BA.2.86 Spike Protein with ACE2 Host Receptor and Antibodies: Compensatory Functional Effects of Binding Hotspots in Modulating Mechanisms of Receptor Binding and Immune Escape. *Journal of Chemical Information and Modeling*, 2024, 64, 1657-1681. [[link](https://doi.org/10.1021/acs.jcim.3c01857)]
- Alshahrani, M.; Gupta, G.; **Xiao, S.**; Tao, P.; Verkhivker, G. Comparative Analysis of Conformational Dynamics and Systematic Characterization of Cryptic Pockets in the SARS-CoV-2 Omicron BA.2, BA.2.75 and XBB.1 Spike Complexes with the ACE2 Host Receptor: Confluence of Binding and Structural Plasticity in Mediating Networks of Conserved Allosteric Sites. *Viruses*, 2023, 15(10), 2073. [[link](https://doi.org/10.3390/v15102073)]
- Tian, H.; **Xiao, S.**; Jiang, X.; Tao, P. PASSerRank: prediction of allosteric sites with learning to rank. *Journal of Computational Chemistry*, 2023, 44, 2223-2229. [[link](https://doi.org/10.1002/jcc.27193)]
- **Xiao, S.**^\#^; Alshahrani, M; Gupta, G; Tao, P; Verkhivker, G. Markov State Models and Perturbation-Based Approaches Reveal Distinct Dynamic Signatures and Hidden Allosteric Pockets in the Emerging SARS-Cov-2 Spike Omicron Variants Complexes with the Host Receptor: The Interplay of Dynamics and Convergent Evolution Modulates Allostery and Functional Mechanisms. *Journal of Chemical Information and Modeling*, 2023, 63, 5272–5296. [[link](https://doi.org/10.1021/acs.jcim.3c00778)]
- Verkhivker, G.; Alshahrani, M; Gupta, G; **Xiao, S**; Tao, P. Probing Conformational Landscapes of Binding and Allostery in the SARS-CoV-2 Omicron Variant Complexes Using Microsecond Atomistic Simulations and Perturbation-Based Profiling Approaches: Hidden Role of Omicron Mutations as Modulators of Allosteric Signaling and Epistatic Relationships. *Physical Chemistry Chemical Physics*, 2023, 25, 21245-21266. [[link](https://doi.org/10.1039/D3CP02042H)]
- Tian, H.; **Xiao, S.**; Jiang, X.; Tao, P. PASSer: Fast and Accurate Prediction of Protein Allosteric Sites. *Nucleic Acids Research*, 2023, 51, W427–W431. [[link](https://doi.org/10.1093/nar/gkad303)]
- Verkhivker, G.; Alshahrani, M.; Gupta, G.; **Xiao, S.**; Tao, P. From Deep Mutational Mapping of Allosteric Protein Landscapes to Deep Learning of Allostery and Hidden Allosteric Sites: Zooming in on “Allosteric Intersection” of Biochemical and Big Data Approaches. *International Journal of Molecular Sciences*, 2023, 24, 7747. [[link](https://doi.org/10.3390/ijms24097747)]
- Li, H.; Tian, H; Chen, Y.; **Xiao, S.**, Zhao, X;, Gao, Y; Zhang, L. Analyzing and Predicting the Viscosity of Polymer Nanocomposites in the Conditions of Temperature, Shear Rate, and Nanoparticle Loading with Molecular Dynamics Simulations and Machine Learning. *The Journal of Physical Chemistry B*, 2023, 127, 3596–3605. [[link](https://doi.org/10.1021/acs.jpcb.3c01697)]
- **Xiao, S.**^\#^; Song, Z.; Tian, H.; Tao, P. Assessments of Variational Autoencoder in Protein Conformation Exploration. *Journal of Computational Biophysics and Chemistry*, 2023, 22, 489-501. [[link](https://doi.org/10.1142/S2737416523500217)]
- **Xiao, S.**^\#\*^; Verkhivker, G.; Tao, P. Machine Learning and Protein Allostery. *Trends in Biochemical Sciences*, 2022, 48, 375-390. [[link](https://doi.org/10.1016/j.tibs.2022.12.001)]
- Tian, H.; Jiang, X.; **Xiao, S.**; La Force, H.; Larson, E. C.; Tao, P. LAST: Latent Space-Assisted Adaptive Sampling for Protein Trajectories. *Journal of Chemical Information and Modeling*, 2023, 63, 67–75. [[link](https://doi.org/10.1021/acs.jcim.2c01213)]
- **Xiao, S.**^\#^; Tian, H.; Tao, P. PASSer2.0: Accurate Prediction of Protein Allosteric Sites Through Automated Machine Learning. *Frontiers in Molecular Biosciences*, 2022, 9. [[link](https://doi.org/10.3389/fmolb.2022.879251)]
- Tian, H.; Jiang, X.; Trozzi, F.; **Xiao, S.**; Larson, E. C.; Tao, P. Explore Protein Conformational Space With Variational Autoencoder. *Frontiers in Molecular Biosciences*, 2021, 8. [[link](https://doi.org/10.3389/fmolb.2021.781635)]


## Academic Awards

- **Jan. 2024** Theoretical and Computational Chemistry Research Achievement Award, SMU
- **May. 2023** Graduate Research Achievement Award (2022-2023 academic year), SMU
- **Apr. 2023** 3rd Place Price in Physical/Computational Chemistry Section, 55th ACS DFW Annual Meeting-in-Miniature [[link](https://acsdfw.org/meeting-in-miniature/)]
- **Apr. 2023** Computational Science and Engineering graduate fellowship (2023-2024, $25,000 in total), SMU
- **Dec. 2022** Theoretical and Computational Chemistry Research Achievement Award, SMU
- **Nov. 2021** Runner-up Three Minute Thesis Competition, SMU [[link](https://www.smu.edu/Moody/Events/Three-Minute-Thesis)]
- **Mar. 2020** University Ph.D. Fellowship (2020-2024, $32,000 in total), SMU [[link](https://www.smu.edu/moody/funding/university-phd-fellows/sian-xiao)]
- **Nov. 2017** Outstanding student of College of Materials Science and Engineering, BUCT
- **May. 2017** First Prize, Mathematical Contest in Modeling, BUCT
- **Nov. 2016** Outstanding student of College of Science, BUCT
- **Sep. 2015** Outstanding student of University, BUCT


# Conferences And Presentations

- **Aug. 2023** Poster Presentation, ACS Fall 2023, San Francisco, CA, US
- **May. 2023** MolSSI workshop: Machine Learning and Chemistry: Are We There Yet?, College Park, MD, US
- **Apr. 2023** Oral Presentation, 55^th^ ACS DFW Annual Meeting-in-Miniature, Stephenville, TX, US
- **Mar. 2023** i-CoMSE Enhanced Sampling Virtual School 2023
- **Feb. 2023** 28^th^ Austin Symposium on Molecular Structure and Dynamics at Dallas (ASMD@D), Dallas, TX, US
- **Mar. 2022** Poster Presentation, ACS Spring 2022, San Diego, CA, US
- **Nov. 2021** Three Minute Thesis, SMU, Dallas, TX, US
